# Generated by Django 4.0.6 on 2022-07-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image')),
                ('file', models.FileField(upload_to='pfd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.resumeuser')),
            ],
        ),
    ]
