# Generated by Django 4.0.6 on 2022-07-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
