# Generated by Django 4.0.6 on 2022-07-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
